// Convert snarkjs verification_key.json files into a Rust module of
// groth16_solana::groth16::Groth16Verifyingkey constants.
//
// Usage: node vkey-to-rust.mjs <vkey.json> <CONST_NAME> [<vkey.json> <CONST_NAME> ...]
//
// Point encoding matches the alt_bn128 syscalls (EVM precompile layout):
// G1 = x||y as 32-byte big-endian; G2 = x_c1||x_c0||y_c1||y_c0.
// Nothing is negated here — only the *proof's* A point is negated, client-side.
import { readFileSync } from "node:fs";

function feBytes(dec) {
  let v = BigInt(dec);
  const out = new Array(32);
  for (let i = 31; i >= 0; i--) {
    out[i] = Number(v & 0xffn);
    v >>= 8n;
  }
  return out;
}

const g1Bytes = (p) => [...feBytes(p[0]), ...feBytes(p[1])];
const g2Bytes = (p) => [
  ...feBytes(p[0][1]),
  ...feBytes(p[0][0]),
  ...feBytes(p[1][1]),
  ...feBytes(p[1][0]),
];

function rustArray(bytes, indent) {
  const lines = [];
  for (let i = 0; i < bytes.length; i += 16) {
    lines.push(indent + bytes.slice(i, i + 16).join(", ") + ",");
  }
  return lines.join("\n");
}

function emit(vkeyPath, constName) {
  const vk = JSON.parse(readFileSync(vkeyPath, "utf8"));
  if (vk.protocol !== "groth16" || String(vk.curve).toLowerCase() !== "bn128") {
    throw new Error(`${vkeyPath}: expected groth16/bn128, got ${vk.protocol}/${vk.curve}`);
  }
  const ic = vk.IC.map((p) => `    [\n${rustArray(g1Bytes(p), "        ")}\n    ],`).join("\n");
  return `pub const ${constName}: Groth16Verifyingkey = Groth16Verifyingkey {
    nr_pubinputs: ${vk.IC.length - 1},
    vk_alpha_g1: [
${rustArray(g1Bytes(vk.vk_alpha_1), "        ")}
    ],
    vk_beta_g2: [
${rustArray(g2Bytes(vk.vk_beta_2), "        ")}
    ],
    vk_gamme_g2: [
${rustArray(g2Bytes(vk.vk_gamma_2), "        ")}
    ],
    vk_delta_g2: [
${rustArray(g2Bytes(vk.vk_delta_2), "        ")}
    ],
    vk_ic: &[
${ic}
    ],
};
`;
}

const args = process.argv.slice(2);
if (args.length < 2 || args.length % 2 !== 0) {
  console.error("usage: node vkey-to-rust.mjs <vkey.json> <CONST_NAME> ...");
  process.exit(1);
}

let out = `//! GENERATED by scripts/vkey-to-rust.mjs — do not edit.
//! Regenerate with scripts/setup.sh after any circuit change.

use groth16_solana::groth16::Groth16Verifyingkey;

`;
for (let i = 0; i < args.length; i += 2) {
  out += emit(args[i], args[i + 1]) + "\n";
}
process.stdout.write(out);
